<a href="https://colab.research.google.com/github/ziedjouini/NLP/blob/main/NLP_6_Sentiment_analysis_zied.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import nltk

nltk.download('popular')

In [ ]:
# Load in the necessary libraries and the dataset
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, r2_score
import matplotlib.pyplot as plt

In [ ]:
train = pd.read_csv('https://github.com/xxjjxj945/NLP4-Big-of-words/blob/main/train.csv?raw=true')
train

textID                                               text  \
0      cb774db0d1                I`d have responded, if I were going   
1      549e992a42      Sooo SAD I will miss you here in San Diego!!!   
2      088c60f138                          my boss is bullying me...   
3      9642c003ef                     what interview! leave me alone   
4      358bd9e861   Sons of ****, why couldn`t they put them on t...   
...           ...                                                ...   
27475  4eac33d1c0   wish we could come see u on Denver  husband l...   
27476  4f4c4fc327   I`ve wondered about rake to.  The client has ...   
27477  f67aae2310   Yay good for both of you. Enjoy the break - y...   
27478  ed167662a5                         But it was worth it  ****.   
27479  6f7127d9d7     All this flirting going on - The ATG smiles...   

                                           selected_text sentiment  
0                    I`d have responded, if I were going   neutral  
1                                               Sooo SAD  negative  
2                                            bullying me  negative  
3                                         leave me alone  negative  
4                                          Sons of ****,  negative  
...                                                  ...       ...  
27475                                             d lost  negative  
27476                                      , don`t force  negative  
27477                          Yay good for both of you.  positive  
27478                         But it was worth it  ****.  positive  
27479  All this flirting going on - The ATG smiles. Y...   neutral  

[27480 rows x 4 columns]

In [ ]:
#https://pandas.pydata.org/docs/getting_started/intro_tutorials/03_subset_data.html
train_1=train[train["sentiment"].isin(['positive', 'negative'])]
train_1

textID                                               text  \
1      549e992a42      Sooo SAD I will miss you here in San Diego!!!   
2      088c60f138                          my boss is bullying me...   
3      9642c003ef                     what interview! leave me alone   
4      358bd9e861   Sons of ****, why couldn`t they put them on t...   
6      6e0c6d75b1  2am feedings for the baby are fun when he is a...   
...           ...                                                ...   
27474  b78ec00df5                                     enjoy ur night   
27475  4eac33d1c0   wish we could come see u on Denver  husband l...   
27476  4f4c4fc327   I`ve wondered about rake to.  The client has ...   
27477  f67aae2310   Yay good for both of you. Enjoy the break - y...   
27478  ed167662a5                         But it was worth it  ****.   

                    selected_text sentiment  
1                        Sooo SAD  negative  
2                     bullying me  negative  
3                  leave me alone  negative  
4                   Sons of ****,  negative  
6                             fun  positive  
...                           ...       ...  
27474                       enjoy  positive  
27475                      d lost  negative  
27476               , don`t force  negative  
27477   Yay good for both of you.  positive  
27478  But it was worth it  ****.  positive  

[16363 rows x 4 columns]

In [ ]:
# nettoyer le texte 
import nltk
import string 
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
"""for punctuation in string.punctuation:
  sentence=sentence.replace(punctuation,'')
sentence"""
#https://www.dataknowsall.com/textcleaning.html
#https://machinelearningmastery.com/clean-text-machine-learning-python/

"for punctuation in string.punctuation:\n  sentence=sentence.replace(punctuation,'')\nsentence"

In [ ]:
from nltk.tokenize import word_tokenize
import string
from nltk.corpus import stopwords
import spacy


/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


In [ ]:
"""# split into words
from nltk.tokenize import word_tokenize
tokens = word_tokenize(text)
# convert to lower case
tokens = [w.lower() for w in tokens]
# remove punctuation from each word
import string
table = str.maketrans('', '', string.punctuation)
stripped = [w.translate(table) for w in tokens]
# remove remaining tokens that are not alphabetic
words = [word for word in stripped if word.isalpha()]
# filter out stop words
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
words = [w for w in words if not w in stop_words]
print(words[:100])"""

In [ ]:
"""def clean(sentence):
  for punctuation in string.punctuation:
    sentence=sentence.replace(punctuation,'')
  tokens = nltk.word_tokenize(sentence.lower())
  tokens_clean = []
  for words in tokens:
    if words not in nltk.corpus.stopwords.words("english"):
      tokens_clean.append(words)
  words_str=' '.join(tokens_clean)
  return  words_str"""
 

In [ ]:
"""def clean(sentence):
  for punctuation in string.punctuation:
    sentence=sentence.replace(punctuation,'')
  tokens = nltk.word_tokenize(sentence.lower())
  tokens_clean = []
  for words in tokens:
    if words not in nltk.corpus.stopwords.words("english"):
      tokens_clean.append(words)
      words_str=' '.join(tokens_clean)
      
  return words_str"""

# j'ai utilisé deux methodes 


In [ ]:
def clean(sentence):
  nlp = spacy.load('en_core_web_sm')
  sent_tokens = nlp(sentence)
  for token in sent_tokens:
    print(token.lemma_,end=' ')
clean("You are better when I am well.")

you be well when I be well . 

In [ ]:
def clean(sentence):
  nlp = spacy.load('en_core_web_sm')
  sent_tokens = nlp(sentence)
  tokens_lem=[]
  for token in sent_tokens:
    tokens_lem.append(token.lemma_)
    words_str=' '.join(tokens_lem)
  return words_str
clean("You are better when I am well.")

'you be well when I be well .'

***Récupère la liste des stopwords anglais depuis NLTK***

In [ ]:
import nltk
from nltk.corpus import stopwords
print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [ ]:
print(len(stopwords.words('english')))

179


***Complète ta fonction clean pour qu'elle supprime la ponctuation et les stopwords.***

In [ ]:
def clean(sentence):
   # Remove puncuation
  for punctuation in string.punctuation:
    sentence=sentence.replace(punctuation,'')
  nlp = spacy.load('en_core_web_sm')
  sent_tokens = nlp(sentence)
  tokens_lem=[]
  for token in sent_tokens:
    tokens_lem.append(token.lemma_)
    words_str=' '.join(tokens_lem)
  return words_str
clean("You are better when I am; :;/ well.")

'you be well when I be   well'

In [ ]:
nlp = spacy.load('en_core_web_sm')
sent_tokens = nlp(sentence)

In [ ]:
def clean(sentence):
 # tokens = nltk.word_tokenize(sentence.lower())
  sentence=sentence.lower()
  for punctuation in string.punctuation:
    sentence=sentence.replace(punctuation,'')
  nlp = spacy.load('en_core_web_sm')
  sent_tokens = nlp(sentence)
  tokens_lem=[]
  for token in sent_tokens:
    tokens_lem.append(token.lemma_)
  token_clean = [word for word in tokens_lem if not word.lower() in stopwords.words('english')]
  words_str=' '.join(token_clean)

  return words_str
clean("You are better when I am; :;/ well.")

'well   well'

In [ ]:
" ".join(["coucou", "hello"])

'coucou hello'

In [ ]:
from nltk.stem import WordNetLemmatizer
def clean(sentence):
  for punctuation in string.punctuation:
    sentence=sentence.replace(punctuation,'')
  str=' '
  lemmatizer=WordNetLemmatizer()
  lemmatized=[lemmatizer.lemmatize(word) for word in sentence]
  str=''.join(lemmatized)
  return str
clean("You are? better when I ; , am well.")

'You are better when I   am well'

In [ ]:
from nltk.stem import WordNetLemmatizer
def clean(sentence):
  str=' '
  tokens = word_tokenize(sentence)
  # convert to lower case
  tokens = [w.lower() for w in tokens]
  for punctuation in string.punctuation:
    sentence=sentence.replace(punctuation,'')
  useless_words = nltk.corpus.stopwords.words("english")
  [word for word in sentence if not word in useless_words]
  lemmatizer=WordNetLemmatizer()
  lemmatized=[lemmatizer.lemmatize(word) for word in sentence]
  str=''.join(lemmatized)
  return str
clean("You are? better when I ;  , am well.")

'You are better when I    am well'

In [ ]:
from nltk.stem import WordNetLemmatizer

lemmatizer=WordNetLemmatizer()

In [ ]:
def lemming(sentence):
  for punctuation in string.punctuation:
    sentence=sentence.replace(punctuation,'')
  lemm = nltk.word_tokenize(sentence.lower())
    #stemmed_content = stemmed_content.lower()
    #stemmed_content = stemmed_content.split()
  lemm = [word for word in lemm if not word in stopwords.words('english')]
  lemm =' '.join(lemm)
  return lemm
lemming("You are? better when I ;  , am well.")

'better well'

In [ ]:
def lemming(sentence):
  #tokens = nltk.word_tokenize(sentence.lower())
  for punctuation in string.punctuation:
    sentence=sentence.replace(punctuation,'')
  lemm = nltk.word_tokenize(sentence.lower())
    #stemmed_content = stemmed_content.lower()
    #stemmed_content = stemmed_content.split()
  #lemm = [word for word in lemm if not word in stopwords.words('english')]
  
  lemm =' '.join(lemm)
  return lemm

In [ ]:
lemming("You are? better when I ;  , am well.")

'better well'

In [ ]:
def clean(sentence):
  
  nlp = spacy.load('en_core_web_sm')
  doc  = nlp(sentence)
  lemm=[token.lemma_ for token in doc]
  
  text=" ".join(lemm)

  return text
clean("You are better when I am well.")

'you be well when I be well .'

In [ ]:
from nltk.stem.porter import PorterStemmer
port_stem = PorterStemmer()

In [ ]:
def clean_1(sentence):
  tokens = nltk.word_tokenize(sentence.lower())
  for punctuation in string.punctuation:
    sentence=sentence.replace(punctuation,'')
  nlp = spacy.load('en_core_web_sm')
  doc  = nlp(sentence)
  lemm=[token.lemma_ for token in doc]
  lemm= [port_stem.stem(word) for word in lemm if not word in stopwords.words('english')]
  text=" ".join(lemm)

  return text
clean("You are better when I am well.")

'you be well when I be well'

In [ ]:
"""import re
def stemming(content):

    for punctuation in string.punctuation:
      stemmed_content=content.replace(punctuation,'')
    stemmed_content=nltk.word_tokenize(content.lower())
    stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
    stemmed_content = ' '.join(stemmed_content)
   
    return stemmed_content
stemming("You are better./ when § I am well.")"""

'import re\ndef stemming(content):\n\n    for punctuation in string.punctuation:\n      stemmed_content=content.replace(punctuation,\'\')\n    stemmed_content=nltk.word_tokenize(content.lower())\n    stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words(\'english\')]\n    stemmed_content = \' \'.join(stemmed_content)\n   \n    return stemmed_content\nstemming("You are better./ when § I am well.")'

In [ ]:
nlp = spacy.load('en_core_web_sm')
def clean_2(sentence):
 # tokens = nltk.word_tokenize(sentence.lower())
  sentence=sentence.lower()
  for punctuation in string.punctuation:
    sentence=sentence.replace(punctuation,'')
  
  sent_tokens = nlp(sentence)
  tokens_lem=[]
  for token in sent_tokens:
    tokens_lem.append(token.lemma_)
  token_clean = [word for word in tokens_lem if not word.lower() in stopwords.words('english')]
  words_str=' '.join(token_clean)

  return words_str.strip()
clean("You are better when I am; :;/ well.")

'well   well'

In [ ]:
train_1['lemma'] = train_1['text'].apply(clean_2)

<ipython-input-14-1a0b0be8772c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_1['lemma'] = train_1['text'].apply(clean_2)


In [ ]:
train_1

textID                                               text  \
1      549e992a42      Sooo SAD I will miss you here in San Diego!!!   
2      088c60f138                          my boss is bullying me...   
3      9642c003ef                     what interview! leave me alone   
4      358bd9e861   Sons of ****, why couldn`t they put them on t...   
6      6e0c6d75b1  2am feedings for the baby are fun when he is a...   
...           ...                                                ...   
27474  b78ec00df5                                     enjoy ur night   
27475  4eac33d1c0   wish we could come see u on Denver  husband l...   
27476  4f4c4fc327   I`ve wondered about rake to.  The client has ...   
27477  f67aae2310   Yay good for both of you. Enjoy the break - y...   
27478  ed167662a5                         But it was worth it  ****.   

                    selected_text sentiment  \
1                        Sooo SAD  negative   
2                     bullying me  negative   
3                  leave me alone  negative   
4                   Sons of ****,  negative   
6                             fun  positive   
...                           ...       ...   
27474                       enjoy  positive   
27475                      d lost  negative   
27476               , don`t force  negative   
27477   Yay good for both of you.  positive   
27478  But it was worth it  ****.  positive   

                                                   lemma  
1                                sooo sad miss san diego  
2                                             boss bully  
3                                  interview leave alone  
4                    son   could put release already buy  
6                           2 feeding baby fun smile coo  
...                                                  ...  
27474                                     enjoy ur night  
27475  wish could come see u denver   husband lose jo...  
27476  wonder rake   client make clear net force devs...  
27477  yay good enjoy break   probably need hectic we...  
27478                                              worth  

[16363 rows x 5 columns]

In [ ]:
print(train_1['lemma'])

1                                  sooo sad miss san diego
2                                               boss bully
3                                    interview leave alone
4                      son   could put release already buy
6                             2 feeding baby fun smile coo
                               ...                        
27474                                       enjoy ur night
27475    wish could come see u denver   husband lose jo...
27476    wonder rake   client make clear net force devs...
27477    yay good enjoy break   probably need hectic we...
27478                                                worth
Name: lemma, Length: 16363, dtype: object


In [ ]:
X=train_1['lemma']
y=train_1['sentiment']

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=32,train_size=0.75)

In [ ]:
X_train.shape,X.shape,y_train.shape,y.shape

((12272,), (16363,), (12272,), (16363,))

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
cv.fit(X_train,y_train)

CountVectorizer()

In [ ]:
X_train_cv=cv.fit_transform(X_train)

In [ ]:
vectorizer = CountVectorizer()
X_train_cv = vectorizer.fit_transform(X_train)
vectorizer.get_feature_names_out()

array(['00', '0003', '007', ..., '½you', '½z', '½ï'], dtype=object)

In [ ]:
print(X_train_cv.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
cv = CountVectorizer(stop_words='english')
X_train_cv = cv.fit_transform(X_train)

cv.get_feature_names_out()


array(['00', '0003', '007', ..., '½you', '½z', '½ï'], dtype=object)

In [ ]:
print(X_train_cv.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
cv = CountVectorizer()
X_train_cv = cv.fit_transform(X_train)
X_test_cv=cv.transform(X_test)
cv.get_feature_names_out()

array(['00', '0003', '007', ..., '½you', '½z', '½ï'], dtype=object)

In [ ]:
X_test_cv.toarray().shape

(4091, 14763)

In [ ]:
sparse_matrix = vectorizer.transform(X_test)
sparse_matrix

<4091x14763 sparse matrix of type '<class 'numpy.int64'>'
	with 25124 stored elements in Compressed Sparse Row format>

In [ ]:
model = LogisticRegression().fit(X_train_cv,y_train)

print("score d'exactitude (accuracy) sur l'ensemble d'entraînement :",model.score(X_train_cv, y_train))
print("score d'exactitude (accuracy) sur l'ensemble de test :",model.score(X_test_cv, y_test))

score d'exactitude (accuracy) sur l'ensemble d'entraînement : 0.9547750977835724
score d'exactitude (accuracy) sur l'ensemble de test : 0.8589586898068932


In [ ]:
model.classes_

array(['negative', 'positive'], dtype=object)

In [ ]:
predict=model.predict(X_test_cv)
predict

array(['negative', 'negative', 'negative', ..., 'negative', 'negative',
       'positive'], dtype=object)

In [ ]:
df_pred=pd.DataFrame(predict,columns=['pred_sentiment'])
df_pred

pred_sentiment
0          negative
1          negative
2          negative
3          positive
4          negative
...             ...
4086       negative
4087       negative
4088       negative
4089       negative
4090       positive

[4091 rows x 1 columns]

In [ ]:
df_join_pred=train_1.join(df_pred)
df_join_pred

textID                                               text  \
1      549e992a42      Sooo SAD I will miss you here in San Diego!!!   
2      088c60f138                          my boss is bullying me...   
3      9642c003ef                     what interview! leave me alone   
4      358bd9e861   Sons of ****, why couldn`t they put them on t...   
6      6e0c6d75b1  2am feedings for the baby are fun when he is a...   
...           ...                                                ...   
27474  b78ec00df5                                     enjoy ur night   
27475  4eac33d1c0   wish we could come see u on Denver  husband l...   
27476  4f4c4fc327   I`ve wondered about rake to.  The client has ...   
27477  f67aae2310   Yay good for both of you. Enjoy the break - y...   
27478  ed167662a5                         But it was worth it  ****.   

                    selected_text sentiment  \
1                        Sooo SAD  negative   
2                     bullying me  negative   
3                  leave me alone  negative   
4                   Sons of ****,  negative   
6                             fun  positive   
...                           ...       ...   
27474                       enjoy  positive   
27475                      d lost  negative   
27476               , don`t force  negative   
27477   Yay good for both of you.  positive   
27478  But it was worth it  ****.  positive   

                                                   lemma pred_sentiment  
1                                sooo sad miss san diego       negative  
2                                             boss bully       negative  
3                                  interview leave alone       positive  
4                    son   could put release already buy       negative  
6                           2 feeding baby fun smile coo       positive  
...                                                  ...            ...  
27474                                     enjoy ur night            NaN  
27475  wish could come see u denver   husband lose jo...            NaN  
27476  wonder rake   client make clear net force devs...            NaN  
27477  yay good enjoy break   probably need hectic we...            NaN  
27478                                              worth            NaN  

[16363 rows x 6 columns]

In [ ]:
df_totale=df_join_pred.loc[df_join_pred['sentiment']!=df_join_pred['pred_sentiment']]
df_totale.head(10)

textID                                               text  \
3   9642c003ef                     what interview! leave me alone   
9   fc2cbefa9d   Journey!? Wow... u just became cooler.  hehe....   
11  16fab9f95b  I really really like the song Love Story by Ta...   
16  3440297f8b   S`ok, trying to plot alternatives as we speak...   
18  af3fed7fc3         is back home now      gonna miss every one   
26  852edc3769                                         I`m sorry.   
27  bdc32ea43c  On the way to Malaysia...no internet access to...   
29  d22e6d40a7  Went to sleep and there is a power cut in Noid...   
30  d33f811375  I`m going home now. Have you seen my new twitt...   
32  1c31703aef   If it is any consolation I got my BMI tested ...   

                                        selected_text sentiment  \
3                                      leave me alone  negative   
9                        Wow... u just became cooler.  positive   
11                                               like  positive   
16                                             *sigh*  negative   
18                                               onna  negative   
26                                         I`m sorry.  negative   
27                                       .no internet  negative   
29                      Power back up not working too  negative   
30                                  Quite....heavenly  positive   
32  well so much for being unhappy for about 10 mi...  negative   

                                                lemma pred_sentiment  
3                               interview leave alone       positive  
9         journey wow u become cooler   hehe possible       negative  
11    really really like song love story taylor swift       negative  
16                sok try plot alternative speak sigh       positive  
18                  back home       go miss every one       positive  
26                                              sorry       positive  
27                way malaysiano internet access twit       positive  
29         go sleep power cut noida   power back work       positive  
30       go home see new twitter design quiteheavenly       negative  
32  consolation get bmi test hahaha say obese   we...       positive

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit(X_train,y_train)
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf=tfidf.transform(X_test)
tfidf.get_feature_names_out()

array(['00', '0003', '007', ..., '½you', '½z', '½ï'], dtype=object)

In [ ]:
print(X_test_tfidf.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
X_test_tfidf.toarray().shape

(4091, 14763)

In [ ]:
sparse_matrix = tfidf.transform(X_test)
sparse_matrix

<4091x14763 sparse matrix of type '<class 'numpy.float64'>'
	with 25124 stored elements in Compressed Sparse Row format>

In [ ]:
model = LogisticRegression().fit(X_train_tfidf,y_train)

print("score d'exactitude (accuracy) sur l'ensemble d'entraînement :",model.score(X_train_tfidf, y_train))
print("score d'exactitude (accuracy) sur l'ensemble de test :",model.score(X_test_tfidf, y_test))

score d'exactitude (accuracy) sur l'ensemble d'entraînement : 0.9274771838331161
score d'exactitude (accuracy) sur l'ensemble de test : 0.863847470056221



# ***Bag of Words CV***


In [ ]:
modelcv = LogisticRegression().fit(X_train_cv,y_train)
print("score d'exactitude (accuracy) sur l'ensemble d'entraînement CV :",modelcv.score(X_train_cv, y_train))
print("score d'exactitude (accuracy) sur l'ensemble de test CV :",modelcv.score(X_test_cv, y_test))

score d'exactitude (accuracy) sur l'ensemble d'entraînement CV : 0.9547750977835724
score d'exactitude (accuracy) sur l'ensemble de test CV : 0.8589586898068932


# ***TfIdf-***

In [ ]:
modeltfld = LogisticRegression().fit(X_train_tfidf,y_train)
print("score d'exactitude (accuracy) sur l'ensemble d'entraînement TFLD :",modeltfld.score(X_train_tfidf, y_train))
print("score d'exactitude (accuracy) sur l'ensemble de test TFLS :",modeltfld.score(X_test_tfidf, y_test))

score d'exactitude (accuracy) sur l'ensemble d'entraînement TFLD : 0.9274771838331161
score d'exactitude (accuracy) sur l'ensemble de test TFLS : 0.863847470056221


# ***Conclusion : le mellieur c'est TFLD***

In [ ]:
from sklearn.model_selection import cross_val_score


In [ ]:
# CV

In [ ]:
cross_val_score(LogisticRegression(), 
                X_train_cv, y_train, 
                cv = 6 )

array([0.85874878, 0.8655914 , 0.84841076, 0.85085575, 0.86308068,
       0.85476773])

In [ ]:
cross_val_score(LogisticRegression(), 
                X_train_cv, y_train, 
                cv = 6 ).mean()

0.8569091817297512

In [ ]:
#TFLD

In [ ]:
cross_val_score(LogisticRegression(), 
                X_test_tfidf, y_test, 
                cv = 6 )

array([0.84164223, 0.8255132 , 0.82844575, 0.83870968, 0.83431085,
       0.83700441])

In [ ]:
cross_val_score(LogisticRegression(), 
                X_test_tfidf, y_test, 
                cv = 6 ).mean()

0.8342710176943515